<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE books [
    <!-- <!ELEMENT books> -->
    <!-- <!ELEMENT to (#PCDATA)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT heading (#PCDATA)>
<!ELEMENT body (#PCDATA)> -->
    <!ELEMENT books (book)>
    <!ELEMENT book (title,author,publisher,edition,price)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT author (#PCDATA)>
    <!ELEMENT publisher (#PCDATA)>
    <!ELEMENT edition (#PCDATA)>
    <!ELEMENT price (#PCDATA)>
]>
<?xml-stylesheet type="text/css" href="Rule.css"?>
<books>
    <heading>Welcome </heading>
    <book>
        <title>Title -: Web Programming</title>
        <author>Author -: Chrisbates</author>
        <publisher>Publisher -: Wiley</publisher>
        <edition>Edition -: 3</edition>
        <price> Price -: 400</price>
    </book>
    <book>
        <title>Title -: Internet world-wide-web</title>
        <author>Author -: Paul Ditel</author>
        <publisher>Publisher -: Pearson</publisher>
        <edition>Edition -: 3</edition>
        <price>Price -: 600</price>
    </book>
    <book>
        <title>Title -: Computer Networks</title>
        <author>Author -: Foruouzan</author>
        <publisher>Publisher -: Mc Graw Hill</publisher>
        <edition>Edition -: 5</edition>
        <price>Price -: 700</price>
    </book>
    <book>
        <title>Title -: DBMS Concepts</title>
        <author>Author -: Navath</author>
        <publisher>Publisher -: Oxford</publisher>
        <edition>Edition -: 5</edition>
        <price>Price -: 600</price>
    </book>
    <book>
        <title>Title -: Linux Programming</title>
        <author>Author -: Subhitab Das</author>
        <publisher>Publisher -: Oxford</publisher>
        <edition>Edition -: 8</edition>
        <price>Price -: 300</price>
    </book>
</books>